stages:
  - build

.build_template:
  stage: build
  image:
    name: gitlab-registry.cern.ch/ci-tools/docker-image-builder
    entrypoint: [""]  
  variables:
    DOCKERFILE: docker/Dockerfile
    TAG: run3
    DESTINATION: '${CI_REGISTRY_IMAGE}:${TAG}'
  before_script:
    - |
      echo "{
        \"auths\": {
          \"$CI_REGISTRY\": {
            \"username\": \"$CI_REGISTRY_USER\",
            \"password\": \"$CI_REGISTRY_PASSWORD\"
          },
          \"https://index.docker.io/v1/\": {
            \"username\": \"$DOCKERHUB_USER\",
            \"password\": \"$DOCKERHUB_TOKEN\"
          }
        }
      }" > /kaniko/.docker/config.json

  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile ${DOCKERFILE} --destination ${DESTINATION} --destination docker.io/${DOCKERHUB_USER}/timber:${TAG} --force
  rules:
    - if: '$CI_COMMIT_BRANCH == "Run3_docker"'

build-run3-image:
  extends: .build_template